"""Stable constants for PHOENIX v21.150."""
MODULE_VERSION = "21.150"
MODULE_NAME = "containment-effectiveness-observation-quarantine-resolution-readiness-governance"
ADMISSION_STATE = "fallback-ready"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "resolution-ready"
DEGRADED_STATE = "degraded"
MIN_CAPABILITY_AVAILABILITY = 0.95
MIN_FALLBACK_HEALTH = 0.90
MIN_DEPENDENCY_SATISFACTION = 0.95
MIN_CONFIDENCE = 0.80
MIN_FRESHNESS = 0.75
MAX_RESIDUAL_RISK = 0.20
AUTONOMOUS_FALLBACK_ACTIVATION = False
AUTONOMOUS_QUARANTINE_RESOLUTION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
