"""Stable constants for PHOENIX v21.160."""
MODULE_VERSION = "21.160"
MODULE_NAME = "coordinated-recovery-stability-observation-remediation-episode-closure-governance"
ADMISSION_STATE = "completed"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "closed"
FAIL_CLOSED_STATE = "degraded"
DEFAULT_MIN_STABILITY_SCORE = 0.80
DEFAULT_MIN_CONFIDENCE = 0.80
DEFAULT_MAX_RESIDUAL_RISK = 0.20
AUTONOMOUS_CONSUMER_MUTATION = False
AUTONOMOUS_BASELINE_MUTATION = False
AUTONOMOUS_ROUTE_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_EXECUTION = False
