"""Stable constants for PHOENIX v21.143."""
MODULE_VERSION = "21.143"
MODULE_NAME = "incident-episode-closure-reliability-baseline-update-governance"
ADMISSION_STATE = "stable"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "closed"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_BASELINE_ADJUSTMENT = 0.05
MIN_CLOSURE_CONFIDENCE = 0.75
MAX_CLOSURE_RESIDUAL_RISK = 0.25
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_BASELINE_MUTATION = False
