"""Stable constants for PHOENIX v21.149."""
MODULE_VERSION = "21.149"
MODULE_NAME = "quarantine-fleet-impact-dependency-containment-governance"
ADMISSION_STATE = "quarantined"
REVIEW_STATE = "review-required"
APPROVED_STATE = "approved"
FALLBACK_READY_STATE = "fallback-ready"
FAIL_CLOSED_STATE = "blocked"
MAX_AFFECTED_CONSUMERS_FOR_LOW_BLAST_RADIUS = 5
AUTONOMOUS_FALLBACK_ACTIVATION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_EXECUTION = False
