"""Stable constants for PHOENIX v21.153."""
MODULE_VERSION = "21.153"
MODULE_NAME = "quarantine-episode-closure-reintegration-reliability-feedback-governance"
ADMISSION_STATE = "stable"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "closed"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_RELIABILITY_ADJUSTMENT = 0.05
MIN_CLOSURE_CONFIDENCE = 0.80
MAX_CLOSURE_RESIDUAL_RISK = 0.20
AUTONOMOUS_RUNTIME_MUTATION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_BASELINE_MUTATION = False
AUTONOMOUS_RELIABILITY_MUTATION = False
