"""Stable constants for PHOENIX v21.154."""
MODULE_VERSION = "21.154"
MODULE_NAME = "reintegration-reliability-baseline-proposal-impact-preview-governance"
ADMISSION_STATE = "closed"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "approved-preview"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_SCORE_DELTA = 0.10
DEFAULT_MAX_BLAST_RADIUS = 0.30
DEFAULT_MAX_RESIDUAL_RISK = 0.25
SIMULATION_ONLY = True
AUTONOMOUS_BASELINE_MUTATION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
