"""Stable constants for PHOENIX v21.152."""
MODULE_VERSION = "21.152"
MODULE_NAME = "reintegration-stability-observation-post-quarantine-confidence-governance"
ADMISSION_STATE = "reintegrated"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "stable"
FAIL_CLOSED_STATE = "degraded"
DEFAULT_MAX_LATENCY_MS = 1000.0
DEFAULT_MAX_ERROR_RATE = 0.05
DEFAULT_MIN_CONFIDENCE = 0.80
DEFAULT_MAX_RESIDUAL_RISK = 0.25
AUTONOMOUS_QUARANTINE_CLOSURE = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_EXECUTION = False
