"""Stable constants for PHOENIX v21.162."""
MODULE_VERSION = "21.162"
MODULE_NAME = "reliability-feedback-impact-simulation-baseline-change-preview-governance"
ADMISSION_STATE = "approved-feedback"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "approved-preview"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_SCORE_DELTA = 0.12
DEFAULT_MAX_BLAST_RADIUS = 0.35
DEFAULT_MAX_RESIDUAL_RISK = 0.25
SIMULATION_ONLY = True
AUTONOMOUS_BASELINE_MUTATION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
EXECUTION_ENABLED = False
