"""Stable constants for PHOENIX v21.161."""
MODULE_VERSION = "21.161"
MODULE_NAME = "remediation-outcome-reliability-learning-baseline-feedback-governance"
ADMISSION_STATE = "closed"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "approved-feedback"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_BASELINE_ADJUSTMENT = 0.05
DEFAULT_MIN_CONFIDENCE = 0.80
DEFAULT_MAX_RESIDUAL_RISK = 0.20
MIN_STABILITY = 0.80
AUTONOMOUS_BASELINE_MUTATION = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
AUTONOMOUS_EXECUTION = False
