"""Stable constants for PHOENIX v21.163."""
MODULE_VERSION = "21.163"
MODULE_NAME = "versioned-reliability-baseline-proposal-controlled-commit-governance"
ADMISSION_STATE = "approved-preview"
REVIEW_STATE = "review-required"
SUCCESS_STATE = "committed"
FAIL_CLOSED_STATE = "blocked"
DEFAULT_MAX_DELTA = 0.05
BASELINE_VALUE_MIN = 0.0
BASELINE_VALUE_MAX = 1.0
AUTONOMOUS_BASELINE_ACTIVATION = False
AUTONOMOUS_CONSUMER_ROLLOUT = False
AUTONOMOUS_ROUTING_MUTATION = False
AUTONOMOUS_POLICY_MUTATION = False
