const $=id=>document.getElementById(id);
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
let recognition=null;
let lastAnswer='';
const setStatus=(text,listening=false)=>{const status=$('voice-status');status.textContent=text;$('voice-orb').classList.toggle('listening',listening)};
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){let message=`HTTP ${response.status}`;try{message=(await response.json()).detail||message}catch{}throw new Error(message)}return response.json()};
function setupRecognition(){if(!SpeechRecognition){setStatus('Spracherkennung wird in diesem Browser nicht unterstützt. Du kannst den Befehl tippen.');$('voice-orb').disabled=true;return}recognition=new SpeechRecognition();recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>setStatus('Ich höre zu…',true);recognition.onend=()=>setStatus('Bereit');recognition.onerror=event=>setStatus(`Mikrofonfehler: ${event.error}`);recognition.onresult=event=>{let text='';for(let i=event.resultIndex;i<event.results.length;i++)text+=event.results[i][0].transcript;$('transcript').value=text.trim()}}
function startListening(){if(!recognition)return;recognition.lang=$('language').value;try{recognition.start()}catch{}}
async function sendCommand(){const text=$('transcript').value.trim();if(!text)return setStatus('Bitte sprich oder tippe einen Befehl.');setStatus('JARVIS verarbeitet…');$('answer').textContent='Verarbeitung…';try{const result=await api('/v1/commands/natural',{method:'POST',body:JSON.stringify({text,execute:!$('preview').checked})});lastAnswer=JSON.stringify(result,null,2);$('answer').textContent=lastAnswer;setStatus('Antwort bereit');speak(lastAnswer)}catch(error){lastAnswer=`Fehler: ${error.message}`;$('answer').textContent=lastAnswer;setStatus(lastAnswer)}}
function speak(text){if(!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text.slice(0,2500));utterance.lang=$('language').value;utterance.rate=1;window.speechSynthesis.speak(utterance)}
$('voice-orb').addEventListener('click',startListening);$('send').addEventListener('click',sendCommand);$('speak-answer').addEventListener('click',()=>speak(lastAnswer));$('transcript').addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter')sendCommand()});setupRecognition();
